# Google App Engine - Python Application Configurations
# https://developers.google.com/appengine/docs/python/config/appconfig

# If you're looking for more than just the server configs and need
# a functional complete application to use as the basis for your app,
# checkout: https://github.com/coto/gae-boilerplate.

application: your-app-name
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

# (!) The expires headers are set pretty far in the future. If you don't control
# versioning with filename-based cache busting, consider lowering the cache time
# for resources like CSS and JS to something like 1 week.

handlers:

# Audio

- url: /(.*\.(m4a|f4a|f4b))
  mime_type: audio/mp4
  static_files: static/\1
  upload: static/(.*\.(m4a|f4a|f4b))
  expiration: "30d"

- url: /(.*\.(oga|ogg))
  mime_type: audio/ogg
  static_files: static/\1
  upload: static/(.*\.(oga|ogg))
  expiration: "30d"


# CSS

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  expiration: "365d"


# Data interchange

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  expiration: "0s"

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)
  expiration: "0s"


# HTML

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "0s"
  http_headers:

    # Better website experience for IE users
    X-UA-Compatible: "IE=edge"

    # Content Security Policy (CSP)
    #Content-Security-Policy: "script-src 'self'; object-src 'self'"


# JavaScript

- url: /(.*\.js)
  mime_type: application/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  expiration: "365d"


# Manifest files

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0s"

- url: /(.*\.webapp)
  mime_type: application/x-web-app-manifest+json
  static_files: static/\1
  upload: static/(.*\.webapp)
  expiration: "0s"


# Video

- url: /(.*\.flv)
  mime_type: video/x-flv
  static_files: static/\1
  upload: static/(.*\.flv)
  expiration: "30d"

- url: /(.*\.(mp4|m4v|f4v|f4p))
  mime_type: video/mp4
  static_files: static/\1
  upload: static/(.*\.(mp4|m4v|f4v|f4p))
  expiration: "30d"

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: static/\1
  upload: static/(.*\.ogv)
  expiration: "30d"

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: static/\1
  upload: static/(.*\.webm)
  expiration: "30d"


# Web feeds

- url: /(.*\.(atom|rss))
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.(atom|rss))
  expiration: "1h"


# Web fonts

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: static/\1
  upload: static/(.*\.eot)
  expiration: "30d"

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: static/\1
  upload: static/(.*\.otf)
  expiration: "30d"

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: static/\1
  upload: static/(.*\.(svg|svgz))
  expiration: "30d"

- url: /(.*\.(ttf|ttc))
  mime_type: application/x-font-ttf
  static_files: static/\1
  upload: static/(.*\.(ttf|ttc))
  expiration: "30d"

- url: /(.*\.woff)
  mime_type: application/font-woff
  static_files: static/\1
  upload: static/(.*\.woff)
  expiration: "30d"


# Other

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: static/\1
  upload: static/(.*\.htc)
  expiration: "30d"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.oex)
  mime_type: application/x-opera-extension
  static_files: static/\1
  upload: static/(.*\.oex)

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: static/\1
  upload: static/(.*\.safariextz)

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: static/\1
  upload: static/(.*\.swf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.vcf)
  mime_type: text/x-vcard
  static_files: static/\1
  upload: static/(.*\.vcf)

- url: /(.*\.vtt)
  mime_type: text/vtt
  static_files: static/\1
  upload: static/(.*\.vtt)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: static/\1
  upload: static/(.*\.webp)

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: static/\1
  upload: static/(.*\.xpi)


# image files
- url: /(.*\.(bmp|gif|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: static/\1
  upload: static/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: static/\1
  upload: static/(.*\.(bz2|gz|rar|tar|tgz|zip))

# If you want a completely static site uncomment the following
# lines and remove the gae.py reference from below.
#
# # index files
# - url: /(.*)/
#   static_files: static/\1/index.html
#   upload: static/(.*)/index.html
#   expiration: "15m"
#
# # site root
# - url: /
#   static_files: static/index.html
#   upload: static/index.html
#   expiration: "15m"

- url: /.*
  script: gae.py
